
export const HTTP_BAD_REQUEST = Number(process.env.HTTP_BAD_REQUEST);
export const HTTP_BAD_REQUEST_MESSAGE = process.env.HTTP_BAD_REQUEST_MESSAGE;
export const HTTP_UNAUTHORIZED = Number(process.env.HTTP_UNAUTHORIZED);
export const HTTP_UNAUTHORIZED_MESSAGE = process.env.HTTP_UNAUTHORIZED_MESSAGE;
export const HTTP_FORBIDDEN = Number(process.env.HTTP_FORBIDDEN);
export const HTTP_FORBIDDEN_MESSAGE = process.env.HTTP_FORBIDDEN_MESSAGE;
export const HTTP_NOT_FOUND = Number(process.env.HTTP_NOT_FOUND);
export const HTTP_NOT_FOUND_MESSAGE = process.env.HTTP_NOT_FOUND_MESSAGE;
export const HTTP_INTERNAL_SERVER_ERROR = Number(process.env.HTTP_INTERNAL_SERVER_ERROR);
export const HTTP_INTERNAL_SERVER_ERROR_MESSAGE = process.env.HTTP_INTERNAL_SERVER_ERROR_MESSAGE;
export const HTTP_SERVICE_UNAVAILABLE = Number(process.env.HTTP_SERVICE_UNAVAILABLE);
export const HTTP_SERVICE_UNAVAILABLE_MESSAGE = process.env.HTTP_SERVICE_UNAVAILABLE_MESSAGE;
